obj-$(CONFIG_TOUCHSCREEN_GOODIX_GTX8)     		+= goodix_ts_i2c.o
obj-$(CONFIG_TOUCHSCREEN_GOODIX_GTX8)           	+= goodix_ts_core.o
obj-$(CONFIG_TOUCHSCREEN_GOODIX_GTX8)           	+= goodix_cfg_bin.o
